### ISSUE TITLE
Vue Example

### ISSUE THREAD

**Issue by jdriesen** [ericblade/quagga2-react-example#13]
Hi Sir,

Wow, this is a great component, with very well written documentation.
Thanks for sharing your knowledge !

Can you please tell us how to use your component with Vue ? 
Example code maybe ?
(I really don't have any React knowledge)

Thanks in advance for any effort.

**Comment by ericblade** [comment]
https://github.com/sin-tanaka/vue-quagga

that could quickly be adapted to use the newer quagga2 :)

**Comment by jdriesen** [comment]
Hi Eric,

Thanks for your reply, though it doesn't help me that much (I'm a newbie...)
I'm still gettting the error "NotReadableError: Could not start source" (On Android Phone... I'm using Quasar...)

I was hoping this would be solved in your newer version, but I don't have any clue how to use it in a Vue App...

Any help would be highly appreciated.
Thanks in advance,

Johnny

**Comment by ericblade** [comment]
Getting that error from what specifically?  That's not a browser error that I've ever heard of.  Though it sounds like permissions.

**Comment by ericblade** [comment]
here's an updated vue2 component https://github.com/DevinNorgarb/vue-quagga-2

no idea on vue3, haven't found one.
