### ISSUE TITLE
Scanning not working

### ISSUE THREAD

**Issue by dineshBD** [ericblade/quagga2-react-example#2]
When I try to scan a barcode it is not showing any result. Any suggestions?

**Comment by ericblade** [comment]
Hi @dineshBD ! My apologies for not getting to this sooner, I hadn't noticed there was an issue filed in this repo. 

My first guess would be that it's probably related to the reader, the default reader in Scanner.js is code_128_reader , and you're probably trying to scan something else . . . but without any further knowledge of what you're doing, all I can do is guess on that.

You may want to try the demo page https://serratus.github.io/quaggaJS/examples/live_w_locator.html .. though that uses the original quagga, i don't presently host an updated example using this version of the lib.

That demo page should allow you to flip various options (including what reader is used) in realtime, so you can tune the settings to a set of values that works for your particular application.

**Comment by dineshBD** [comment]
Thanks I'll check it out. Cheers

**Comment by ericblade** [comment]
I'm hopeful you found some settings that worked?
