### ISSUE TITLE
Is this an active project?

### ISSUE THREAD

**Issue by rhazell-msi** [ericblade/quagga2-react-example#22]
Has anyone used this example recently, with any success...  with React 18?  

I just tried and got a bunch of (deprecated) package warnings and ultimately the following error:

  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

Thanks in advance

**Comment by ericblade** [comment]
This is a simplified version of the one I use, which I'm using react 18.20 in currently, so there shouldn't be any reason it wouldn't work.  There might be some better ways to do it, I don't profess to be an expert at React, but it should work.

... some digging around indicates that this is a problem with webpack v4 and the newer SSL in node 17+

https://github.com/webpack/webpack/issues/14532

To run with node 17+, you can set NODE_OPTIONS=--openssl-legacy-provider in your environment before running.

I've got a mountain of things I'm busy with right now, so if anyone wants to upgrade this to use a newer react+webpack, i'd definitely entertain the pull request :)

Thanks!

**Comment by ericblade** [comment]
Has been upgraded  to use create-react-app and react 18 now
