### ISSUE TITLE
always show not detected

### ISSUE THREAD

**Issue by mzulfanw** [ericblade/quagga2-react-example#35]
Thank you for creating this package

but i faced issue when i using upload and then start to decode the barcode, it always show not detected,

decoder: {
            readers: ['code_39_reader'] 
},

example barcode
![barcode](https://github.com/ericblade/quagga2-react-example/assets/60052964/3640e6f3-38a7-41f0-ba25-9a2c2c83b032)

```
full code
  const onChange = e => {
    const file = e.target.files[0];
    const reader = new FileReader();
    reader.onload = function(event) {
      Quagga.decodeSingle(
        {
          decoder: {
            readers: ['code_39_reader'] 
          },
          locate: true,
          src: event.target.result
        },
        function(result) {
          console.log(result);
          if (result.codeResult) {
            console.log('result', result.codeResult.code);
          } else {
            console.log('not detected');
          }
        }
      );
    };
    reader.readAsDataURL(file);
  };
```
  
  thanks before

**Comment by ericblade** [comment]
Given the example, there is absolutely no whitespace on the edges of the barcode, so it's impossible for the detection algorithm to locate it.  
There is a task here to investigate adding some token whitespace around the image area, particularly when not using the camera, but adding new features is way down on my list of things right now.  

I'd recommend just adding a few pixels of whitespace (like 4 or 5 or so) to each edge of the barcode.  That should give it enough space to find it.  Also make sure that you set a resolution that is large enough to contain the width of the image.

**Comment by mzulfanw** [comment]
Thanks for your answer @ericblade , currently i solved this by changed the package ( because need to implemented ASAP), but thank you so much for the answer and also for creating this
